### ISSUE TITLE
Does not allow escaped delimiters

### ISSUE THREAD

**Issue by MaverickEsq** [KrokodileGlue/birch#2]
## Expected Behavior

Using \ before a delimiter should escape it

## Current Behavior

It does not

## Possible Solution
be better at coding

## Steps to Reproduce

1. Try to escape a delimiter
2. it does not work
3. ????
4. blame jp

## Context (Environment)

This makes the entire feature useless and i want my money back

## Log
```
[14:54] <sloth> s/(\/)/
[14:54] <birch> sloth: unmatched '('
```

**Comment by KrokodileGlue** [comment]
The sed plugin is deprecated by the Lisp functionality. When the Lisp implementation has stabilized sed will be re-implemented as a more flexible Lisp script and this feature will be added.

**Comment by MaverickEsq** [comment]
I am requesting an update on this ticket.

**Comment by KrokodileGlue** [comment]
i fixed it :100: :)
