### ISSUE TITLE
No issue template

### ISSUE THREAD

**Issue by MaverickEsq** [KrokodileGlue/birch#3]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

This github does not have an issue template to allow the ordered reporting of issues
## Expected Behavior

When you go to open an issue it should pre-fill an issue template
## Current Behavior

It currently opens as blank
## Possible Solution

Use github issue templates to prefill with this template https://raw.githubusercontent.com/stevemao/github-issue-templates/master/bugs-only/ISSUE_TEMPLATE.md
## Steps to Reproduce

1. Try to open an issue

## Context (Environment)

This makes it difficult to open issues and rely on issues as a source of information and hard for contributors to read issues

## Detailed Description

I think we should add an automatically filled template like https://raw.githubusercontent.com/stevemao/github-issue-templates/master/bugs-only/ISSUE_TEMPLATE.md this one
## Possible Implementation

https://raw.githubusercontent.com/stevemao/github-issue-templates/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by KrokodileGlue** [comment]
I think I fixed it.
